name: massage
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter_hooks: ^0.18.0
  device_preview: ^1.1.0
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter
  spincircle_bottom_bar: ^2.0.0
  table_calendar: ^3.0.9
  iconsax_flutter: ^1.0.0
  email_validator: ^2.0.1
  flutter_screenutil: ^5.9.0
  clean_calendar: ^1.1.0
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  get_storage: ^2.1.1
  onboarding: ^4.0.2
  dash_chat_2: ^0.0.20
  image_picker: ^1.0.4
  file_picker: ^8.0.3
  intl: ^0.19.0
  pdfx: ^2.6.0
  flutter_document_picker: ^5.2.3
  video_player: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
